class Dic {
  final Map<String, List<String>> dic_eng = {
    "Transportation": ["การขนส่ง", "การเดินทาง"],
    "Car": ["รถยนต์"],
    "Bus": ["รถบัส"],
    "Truck": ["รถบรรทุก"],
    "Motorcycle": ["จักรยานยนต์"],
    "Bicycle": ["จักรยาน"],
    "Train": ["รถไฟ"],
    "Subway": ["รถไฟใต้ดิน"],
    "Tram": ["รถราง"],
    "Airplane": ["เครื่องบิน"],
    "Helicopter": ["เฮลิคอปเตอร์"],
    "Boat": ["เรือ"],
    "Ship": ["เรือสำราญ"],
    "Ferry": ["เรือข้ามฟาก"],
    "Taxi": ["แท็กซี่"],
    "Ride-sharing": ["บริการรถร่วม"],
    "Scooter": ["สกู๊ตเตอร์"],
    "Bus stop": ["ป้ายรถบัส"],
    "Train station": ["สถานีรถไฟ"],
    "Airport": ["สนามบิน"],
    "Port": ["ท่าเรือ"],
    "Dock": ["ท่าเรือ"],
    "Ticket": ["ตั๋ว"],
    "Luggage": ["สัมภาระ"],
    "Suitcase": ["กระเป๋าเดินทาง"],
    "Backpack": ["กระเป๋าเป้"],
    "Passport": ["หนังสือเดินทาง"],
    "Flight": ["เที่ยวบิน"],
    "Departure": ["การออกเดินทาง"],
    "Arrival": ["การมาถึง"],
    "Customs": ["ศุลกากร"],
    "Immigration": ["การตรวจคนเข้าเมือง"],
    "Security check": ["การตรวจความปลอดภัย"],
    "Check-in": ["เช็คอิน"],
    "Gate": ["ประตูทางขึ้นเครื่อง"],
    "Boarding pass": ["บัตรขึ้นเครื่อง"],
    "Layover": ["การหยุดพักระหว่างเที่ยวบิน"],
    "Route": ["เส้นทาง"],
    "Traffic": ["การจราจร"],
    "Congestion": ["การจราจรติดขัด"],
    "Road": ["ถนน"],
    "Highway": ["ทางหลวง"],
    "Pedestrian": ["คนเดินเท้า"],
    "Crosswalk": ["ทางข้าม"],
    "Parking": ["ที่จอดรถ"],
    "Fuel": ["น้ำมัน"],
    "Driver": ["คนขับ"],
    "Passenger": ["ผู้โดยสาร"],
    "Ticket counter": ["เคาน์เตอร์จำหน่ายตั๋ว"],
    "Car rental": ["บริการเช่ารถ"],
    "Carpool": ["การเดินทางร่วมกัน"],
    "Bus fare": ["ค่าโดยสารรถบัส"],
    "Train fare": ["ค่าโดยสารรถไฟ"],
    "Flight ticket": ["ตั๋วเครื่องบิน"],
    "Travel agency": ["บริษัททัวร์"],
    "Road trip": ["การเดินทางทางถนน"],
  };

  static Map<String, List<String>> get entries {
    return Dic().dic_eng;
  }

  Dic();
}
