class dicAnimal {
  final Map<String, List<String>> dicAnimal_eng = {
    "Dog": ["สุนัข"],
    "Cat": ["แมว"],
    "Rabbit": ["กระต่าย"],
    "Hamster": ["แฮมสเตอร์"],
    "Guinea pig": ["หนูตะเภา"],
    "Parrot": ["นกแก้ว"],
    "Goldfish": ["ปลาทอง"],
    "Turtle": ["เต่า"],
    "Cow": ["วัว"],
    "Pig": ["หมู"],
    "Sheep": ["แกะ"],
    "Goat": ["แพะ"],
    "Chicken": ["ไก่"],
    "Duck": ["เป็ด"],
    "Horse": ["ม้า"],
    "Donkey": ["ลา"],
    "Lion": ["สิงโต"],
    "Tiger": ["เสือ"],
    "Elephant": ["ช้าง"],
    "Giraffe": ["ยีราฟ"],
    "Zebra": ["ม้าลาย"],
    "Bear": ["หมี"],
    "Deer": ["กวาง"],
    "Monkey": ["ลิง"],
    "Snake": ["งู"],
    "Lizard": ["กิ้งก่า"],
    "Crocodile": ["จระเข้"],
    "Tortoise": ["เต่าบก"],
    "Fish": ["ปลา"],
    "Dolphin": ["ปลาโลมา"],
    "Whale": ["ปลาวาฬ"],
    "Shark": ["ปลาฉลาม"],
    "Octopus": ["ปลาหมึกยักษ์"],
    "Crab": ["ปู"],
    "Lobster": ["กุ้งมังกร"],
    "Bird": ["นก"],
    "Eagle": ["นกอินทรี"],
    "Owl": ["นกฮูก"],
    "Pigeon": ["นกพิราบ"],
    "Swan": ["หงส์"],
    "Peacock": ["นกยูง"],
    "Ferret": ["เฟอเร็ต"],
    "Chinchilla": ["ชินชิลลา"],
    "Budgerigar": ["นกหงส์หยก"],
    "Hedgehog": ["เม่นแคระ"],
    "Rooster": ["ไก่ตัวผู้"],
    "Hen": ["แม่ไก่"],
    "Goose": ["ห่าน"],
    "Turkey": ["ไก่งวง"],
    "Ox": ["วัวตัวผู้"],
    "Llama": ["ลามะ"],
    "Alpaca": ["อัลปาก้า"],
    "Leopard": ["เสือดาว"],
    "Cheetah": ["ชีตาห์"],
    "Hyena": ["ไฮยีน่า"],
    "Kangaroo": ["จิงโจ้"],
    "Koala": ["โคอาลา"],
    "Panda": ["แพนด้า"],
    "Wolf": ["หมาป่า"],
    "Fox": ["สุนัขจิ้งจอก"],
    "Raccoon": ["แรคคูน"],
    "Hippopotamus": ["ฮิปโปโปเตมัส"],
    "Rhinoceros": ["แรด"],
    "Bat": ["ค้างคาว"],
    "Gecko": ["ตุ๊กแก"],
    "Iguana": ["อีกัวน่า"],
    "Chameleon": ["กิ้งก่าคาเมเลียน"],
    "Frog": ["กบ"],
    "Toad": ["คางคก"],
    "Newt": ["ซาลาแมนเดอร์น้ำ"],
    "Salamander": ["ซาลาแมนเดอร์"],
    "Seahorse": ["ม้าน้ำ"],
    "Seal": ["แมวน้ำ"],
    "Sea lion": ["สิงโตทะเล"],
    "Starfish": ["ปลาดาว"],
    "Jellyfish": ["แมงกะพรุน"],
    "Clownfish": ["ปลาการ์ตูน"],
    "Manta ray": ["กระเบนราหู"],
    "Flamingo": ["นกฟลามิงโก"],
    "Penguin": ["เพนกวิน"],
    "Toucan": ["นกทูแคน"],
    "Woodpecker": ["นกหัวขวาน"],
    "Crow": ["อีกา"],
    "Hawk": ["เหยี่ยว"],
    "Vulture": ["แร้ง"],
  };
  static Map<String, List<String>> get entries {
    return dicAnimal().dicAnimal_eng;
  }

  dicAnimal();
}
