class dicSport {
  final Map<String, List<String>> dicSport_eng = {
    "Football": ["ฟุตบอล"],
    "Soccer": ["ฟุตบอล (แบบสากล)"],
    "Basketball": ["บาสเกตบอล"],
    "Volleyball": ["วอลเลย์บอล"],
    "Baseball": ["เบสบอล"],
    "Rugby": ["รักบี้"],
    "Hockey": ["ฮอกกี้"],
    "Cricket": ["คริกเก็ต"],
    "American football": ["อเมริกันฟุตบอล"],
    "Softball": ["ซอฟต์บอล"],
    "Water polo": ["โปโลน้ำ"],
    "Handball": ["แฮนด์บอล"],
    "Tennis": ["เทนนิส"],
    "Table tennis": ["ปิงปอง"],
    "Badminton": ["แบดมินตัน"],
    "Golf": ["กอล์ฟ"],
    "Boxing": ["มวย"],
    "Karate": ["คาราเต้"],
    "Taekwondo": ["เทควันโด"],
    "Judo": ["ยูโด"],
    "Wrestling": ["มวยปล้ำ"],
    "Archery": ["ยิงธนู"],
    "Fencing": ["ฟันดาบ"],
    "Running": ["วิ่ง"],
    "Cycling": ["ปั่นจักรยาน"],
    "Swimming": ["ว่ายน้ำ"],
    "Skateboarding": ["สเก็ตบอร์ด"],
    "Roller skating": ["โรลเลอร์สเกต"],
    "Motorsport": ["มอเตอร์สปอร์ต"],
    "Skiing": ["สกี"],
    "Snowboarding": ["สโนว์บอร์ด"],
    "Surfing": ["โต้คลื่น"],
    "Climbing": ["ปีนเขา"],
    "Parkour": ["พาร์กัวร์"],
    "Long jump": ["กระโดดไกล"],
    "High jump": ["กระโดดสูง"],
    "Hurdles": ["วิ่งข้ามรั้ว"],
    "Pole vault": ["กระโดดค้ำ"],
    "Shot put": ["ทุ่มน้ำหนัก"],
    "Discus throw": ["ขว้างจักร"],
    "Javelin throw": ["พุ่งแหลน"],
    "Diving": ["ดำน้ำ"],
    "Rowing": ["พายเรือ"],
    "Canoeing": ["พายเรือแคนู"],
    "Sailing": ["แล่นเรือ"],
    "Jet skiing": ["เจ็ตสกี"],
    "Wakeboarding": ["เวคบอร์ด"],
    "Chess": ["หมากรุก"],
    "Esports": ["อีสปอร์ต"],
    "Snooker": ["สนุกเกอร์"],
    "Bowling": ["โบว์ลิ่ง"],
    "Darts": ["ปาเป้า"],
  };
  static Map<String, List<String>> get entries {
    return dicSport().dicSport_eng;
  }

  dicSport();
}
